namespace GameX.IW.Formats
{
    public unsafe static partial class FastFile
    {
        public enum IW3XAssetType : int
        {
            xmodelpieces,
            physpreset,
            xanim,
            xmodel,
            material,
            techset,
            image,
            sound,
            sndcurve,
            loaded_sound,
            col_map_sp,
            col_map_mp,
            com_map,
            game_map_sp,
            game_map_mp,
            map_ents,
            gfx_map,
            lightdef,
            ui_map,
            // not used
            font,
            menufile,
            menu,
            localize,
            weapon,
            snddriverglobals,
            // not used
            fx,
            impactfx,
            aitype,
            // not used
            mptype,
            // not used
            character,
            // not used
            xmodelalias,
            // not used
            rawfile,
            stringtable,
            max,
        }

        public enum IW4XAssetType : int
        {
            physpreset,
            phys_collmap,
            xanim,
            xmodelsurfs,
            xmodel,
            material,
            pixelshader,
            vertexshader,
            vertexdecl,
            techset,
            image,
            sound,
            sndcurve,
            loaded_sound,
            col_map_sp,
            col_map_mp,
            com_map,
            game_map_sp,
            game_map_mp,
            map_ents,
            fx_map,
            gfx_map,
            lightdef,
            ui_map,
            // not used
            font,
            menufile,
            menu,
            localize,
            weapon,
            snddriverglobals,
            // not used
            fx,
            impactfx,
            aitype,
            // not used
            mptype,
            // not used
            character,
            // not used
            xmodelalias,
            // not used
            rawfile,
            stringtable,
            leaderboarddef,
            structureddatadef,
            tracer,
            vehicle,
            addon_map_ents,
            max,
        }

        public enum IW5XAssetType : int
        {
            physpreset,
            phys_collmap,
            xanim,
            xmodelsurfs,
            xmodel,
            material,
            pixelshader,
            vertexshader,
            vertexdecl,
            techset,
            image,
            sound,
            sndcurve,
            loaded_sound,
            col_map_mp,
            com_map,
            glass_map,
            ai_paths,
            vehicle_tracks,
            map_ents,
            fx_map,
            gfx_map,
            lightdef,
            ui_map,
            // not used
            font,
            menufile,
            menu,
            localize,
            attachment,
            weapon,
            snddriverglobals,
            // not used
            fx,
            impactfx,
            surfacefx,
            aitype,
            // not used
            mptype,
            // not used
            character,
            // not used
            xmodelalias,
            // not used
            rawfile,
            scriptfile,
            stringtable,
            leaderboarddef,
            structureddatadef,
            tracer,
            vehicle,
            addon_map_ents,
            max,
            col_map_sp = col_map_mp,
        }

        public enum Oth_AssetType : int
        {
            PhysPreset = 0,
            PhysColMap = 1,
            XAnim = 2,
            XModelSurfs = 3,
            XModel = 4,
            Material = 5,
            PixelShader = 6,
            VertexShader = 7,
            VertexDecl = 8,
            TechSet = 9,
            Image = 10,
            Sound = 11,
            SndCurve = 12,
            LoadedSound = 13,
            ColMapSP = 14,
            ColMapMP = 15,
            ComMap = 16,
            GameMapSP = 17,
            GameMapMP = 18,
            MapEnts = 19,
            FXMap = 20,
            GfxMap = 21,
            LightDef = 22,
            UIMap = 23,
            Font = 24,
            MenuFile = 25,
            Menu = 26,
            Localize = 27,
            Weapon = 28,
            SndDriverGlobals = 29,
            FX = 30,
            ImpactFX = 31,
            AIType = 32,
            MPType = 33,
            Character = 34,
            XModelAlias = 35,
            RawFile = 36,
            StringTable = 37,
            LeaderBoardDef = 38,
            StructuredDataDef = 39,
            Tracer = 40,
            Vehical = 41,
            AddONMapEnts = 42,
            Max = 43
        }
    }
}
